name: Build Electron application for macOS
on:
  - push
jobs:
  electron-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Install dependencies
        run: npm ci
      - name: Prepare build
        run: npm run build1
      - name: Build Electron application
        run: npx electron-builder --publish=never -m
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: dist/*.dmg
