name: Release Electron application when version is published
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        uses: softprops/action-gh-release@v1
  electron-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Build Electron application
        run: |
          cd electron
          npm ci
          npm run build-linux
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "electron/dist/*.AppImage"
  electron-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Build Electron application
        run: |
          cd electron
          npm ci
          npm run build-macos
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "electron/dist/*.dmg"
  electron-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Build Electron application
        run: |
          cd electron
          npm ci
          npm run build-windows
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "electron/dist/*.exe"
