name: Release Electron application when version is published
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  electron-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Install dependencies
        run: npm ci
      - name: Build Electron application
        run: npm run build-linux
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*.AppImage"
  electron-macos:
    runs-on: macos-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Install dependencies
        run: npm ci
      - name: Build Electron application
        run: npm run build-macos
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*.dmg"
  electron-windows:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Install dependencies
        run: npm ci
      - name: Build Electron application
        run: npm run build-windows
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*.exe"
