name: Run test suite
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Set up Node 14.18.1
        uses: actions/setup-node@v2
        with:
          node-version: '14.18.1'
      - name: Install dependencies
        run: npm ci
      - name: Run test suite
        run: npm run test
